### ISSUE TITLE
Q4 2023 Progress Report

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/PIPE-3956-aerial-segmentation#12]
## Client Request

As I said, I'm requesting some information that I can put into out milestone report. This will be going to non-technical stakeholders, so I'll have to break things down for them in regard to our progress both on the land segmentation algorithm, and what will be run on the jetson. If you already have any WIP reports on your side regarding the design that would also be super helpful. 

Information I need regarding all the work you've done from the beginning up until the end of this week:
- Development tools used, and how they were used to develop the land segmentation algorithm
- Data sources used for land segmentation i.e. the images, ABS data, etc. all the inputs
- Possibly a diagram of how the algorithm works, all the layers, outputs and classification etc. something like the screenshot below
- What exactly was put on the devkit (and how its different to the above)
- What performance specs will be assessed on the dev kit (omitting power tests that will be done on my side)
- Remaining steps to land segmentation algorithm completion (all the work that you'll be doing in the weeks after this one) 
- Screen shots of results/segmentation etc. that you think an external stakeholder may find interesting is good too 
- Don't worry about presentation of information/diagrams to me, dot points/basic images and blocks are good and I'll reorganise it to put into the report myself

## Tasks

- [ ] Write brief document explaining development process
- [ ] Detail features of software developed and technical aspects
- [ ] List data sources
- [ ] Provide details of Jetson edge dev kit
- [ ] Details of next steps.
- [ ] Example results.
- [ ] Rudimentary diagram

This will all be put into a markdown document that we can put into a sharepoint word docx as well.
